---
- hosts: wiki
  vars_files:
    - "./vars/app.yml"

  pre_tasks:
    - name: update apt repository
      become: yes
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: install node.js
      become: yes
      apt:
        name:
          - nodejs 
          - yarn
        state: present
    - name: ensure node.js app directory exists
      file:
        path: "{{ node_app_path }}"
        state: directory
        owner: ubuntu
        group: ubuntu
      notify:
        - call in every action
    - name: copy node.js application
      copy:
        src: "{{ item.file }}"
        dest: "{{ node_app_path }}"
        owner: ubuntu
        group: ubuntu
      with_items:
        - { file: './nodejs/app.js' }
        - { file: './nodejs/package.json' }
        - { file: './nodejs/yarn.lock' }
      notify:
        - call in every action
    - name: install node.js packages
      command: "yarn install"
      args:
        chdir: "{{ node_app_path }}"
      notify:
        - call in every action
    - name: launch node.js app
      command: "yarn start"
      args:
        chdir: "{{ node_app_path }}"
      notify:
        - call in every action2
        - call in every action

  handlers:
    - include: "./handlers/msg.yml"
